itpsolution_demand_muc/controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\PasswordChangeForm;
use app\widgets\Alert;
use Yii;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\web\Response;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ]
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            /*'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],*/
        ];
    }

    /**
     * Displays homepage.
     *
     * @return string
     */
    public function actionIndex()
    {
        return $this->render('index');
    }

    /**
     * Login action.
     *
     * @return Response|string
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        }

        $model->password = '';
        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * Change password action.
     *
     * @return string
     * @throws \Throwable
     */
    public function actionPasswordChange()
    {
        $model = new PasswordChangeForm();
        $model->privacyPolicy = Yii::$app->getUser()->getIdentity()->isPrivacyPolicy();

        if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->saveNewPassword()) {
            Alert::addSuccess("Passwort wurde erfolgreich geändert.");
            return $this->goBack();
        }

        return $this->render('password_change', [
            'model' => $model,
        ]);
    }

    /**
     * Logout action.
     *
     * @return Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    /**
     * View imprint
     * @return string
     */
    public function actionImprint()
    {
        return $this->render('imprint');
    }
}

itpsolution_demand_muc/views/layouts/_alerts.php
<?php

/**
 * Alert partial gets all messages from session flash. All flash messages where displayed
 */

use app\assets\AppAsset;
use app\components\Constants;
use app\modules\catalog\models\SearchForm;
use yii\bootstrap\ActiveForm;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;

$session = Yii::$app->session;
$flashes = $session->getAllFlashes();

if (!empty($flashes)) {
    foreach ($flashes as $kind => $messages) {
        if ($kind == 'success') {
            foreach ($messages as $message) {
                 $this->registerJs("showSuccessMessage('$message')");
            }
        } else if ($kind == 'error') {
            foreach ($messages as $message) {
                 $this->registerJs("showErrorMessage('$message')");
            }
        } else {
            foreach ($messages as $message) {
                 $this->registerJs("showNoticeMessage('$message')");
            }
        }
    }
}

?>

itpsolution_demand_muc/views/layouts/_guestheader.php
<?php
/**
 * Created by PhpStorm.
 * User: Isabella Neufeld
 * Date: 10.07.2018
 * Time: 13:06
 */

use yii\bootstrap\NavBar;
use yii\helpers\Html;

?>
<div class="navbar-default navbar-fixed-top">
    <br>
    <br>
    <br>
</div>

itpsolution_demand_muc/views/layouts/_navBar.php
<?php

use app\modules\admin\models\OrganisationSessionForm;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\helpers\Html;

$isGuest = Yii::$app->getUser()->isGuest;

?>

<?php NavBar::begin([
    'brandLabel' => Html::img('@web/images/logo.png', ['class' => 'navbar-brand-logo']),
    'brandUrl' => Yii::$app->getHomeUrl(),
    'options' => [
        'id' => 'mainmenu',
        'class' => 'navbar-default navbar-fixed-top',
    ],
]); ?>

<?= Nav::widget([
    'options' => ['class' => 'navbar-nav'],
    'items' => [

    ]
]); ?>

<?= Nav::widget([
    'options' => ['class' => 'navbar-nav navbar-right'],
    'encodeLabels' => false,
    'items' => [
        $isGuest ?
            ['label' => Yii::t('app', 'login'), 'url' => ['/site/login']] :
            [
                'label' => Yii::t('app', 'Logout ({0})', Yii::$app->getUser()->getIdentity()->username),
                'url' => ['/site/logout'],
                'linkOptions' => ['class'=>'logoutColor','data-method' => 'post']
            ],
    ],
]); ?>

<div id="organisation_dropdown">
    <?= $this->render('@app/modules/admin/views/user/_organisation_dropdown', [
        'model' => new OrganisationSessionForm()
    ]); ?>
</div>
<?php NavBar::end(); ?>

itpsolution_demand_muc/views/layouts/main.php
<?php

/* @var $this \yii\web\View
 * @var $content string
 */

use app\assets\AppAsset;
use yii\helpers\Html;

$bundle = AppAsset::register($this);

?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head(); ?>

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
    <META http-equiv="X-UA-Compatible" content="IE=11">
    <script type="text/javascript">
        var baseUrl = "<?= Yii::$app->getHomeUrl();?>";
    </script>
</head>
<body>
<?php $this->beginBody();
$isGuest = Yii::$app->getUser()->isGuest; ?>

<div id="page" data-login-state="<?= $isGuest ? "logged-out" : "logged-in"; ?>">

    <?php if (!$isGuest) {
        echo $this->render('@app/views/layouts/_navBar');
    } else {
        echo $this->render('@app/views/layouts/_guestheader');
    } ?>

    <h1 id="bw-title-bar" class="title-bar">
        <?php
        if ($this->title == Yii::t('app', 'ITPidea')) {
            echo '<div style="text-transform: none">' . Html::encode($this->title) . "</div>";
        } else {
            echo Html::encode($this->title);
        }
        ?>
    </h1>
    <div id="content" class="container">
        <?php $this->render('@app/views/layouts/_alerts'); ?>
        <?= $content ?>
    </div>
</div>
<footer class="footer">
    <div class="container">
        <ul class="pull-left text-muted footer-links list-inline">
            <li>&copy; Organisation</li>
            <li>·</li>
            <li><?= Html::a('Link', '#', ['target' => '_blank']) ?></li>
            <li><?= Html::a('Impressum', ['/site/imprint']) ?></li>
        </ul>
        <p class="pull-right text-muted">Version <?= Yii::$app->params['version'] ?></p>
</footer>


<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>